---
- name: install wget
  yum: name=wget state=latest

- name: Make opt directory
  command: mkdir -p /opt

- command: cd /opt

- name: download java jdk
  shell: 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jre-8u40-linux-x64.tar.gz"'

- name: unarchive tar gunzip
  shell: 'tar xvf jre-8*.tar.gz'

- name: change permissions
  shell: 'chown -R root: jre1.8.0_40'

- copy: src=jre1.8.0_40 dest=/opt/
- shell: chmod +x /opt/jre1.8.0_40/bin/*

- name: enforce oracle java as main java
  file: src=/opt/jre1.8.0_40/bin/java dest=/usr/bin/java state=link

- name: install elasticsearch rpm key
  command: 'rpm --import http://packages.elasticsearch.org/GPG-KEY-elasticsearch'

- name: Install Log Repositories
  copy: src={{ item }} dest=/etc/yum.repos.d/
  with_fileglob:
    - "*.repo"

- name: Install YUM Packages
  yum: name={{ item }} state=present
  with_items:
    - elasticsearch-1.4.4
    - logstash

- name: Set elastic search network to localhost
  shell: "sed -i 's/#network.host: 192.168.0.1/network.host: localhost/' /etc/elasticsearch/elasticsearch.yml"

- shell: cd /root

- name: Download Kibana
  shell: 'wget https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz'

- name: Extract Kibana
  shell: 'tar xvf kibana-4.0.1-linux-x64.tar.gz'

- name: Copy Kibana to opt
  command: creates="/opt/kibana" mv kibana-4.0.1-linux-x64 /opt/kibana

- name: Copy Kibana Service
  copy: src=kibana4.service dest=/etc/systemd/system/kibana4.service

- name: Copy Logstash configuration files
  copy: src={{ item }} dest=/etc/logstash/conf.d/
  with_fileglob:
    - "*.conf"

- name: Download GeoLiteCity Data
  shell: 'curl -O "http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz"'

- name: Extract GeoLiteCity GZIP
  shell: gunzip GeoLiteCity.dat.gz

- copy: src=GeoLiteCity.dat dest=/etc/logstash/GeoLiteCity.dat

- name: Update OpenSSL TLS Config
  command: 'sed -i "s/^\[ v3_ca \]/\[ v3_ca \]\nsubjectAltName = IP: 10.0.100.90/" /etc/pki/tls/openssl.cnf'

- name: Install logstash-Forward Certificate
  copy: src=logstash-forwarder.crt dest=/etc/pki/tls/certs/logstash-forwarder.crt

- name: Install logstash-Forward Key
  copy: src=logstash-forwarder.key dest=/etc/pki/tls/private/logstash-forwarder.key

- name: Install Services
  copy: src=kibana4.service dest=/etc/systemd/system/kibana4.service

- name: Enable Services
  shell: systemctl enable {{ item }}
  with_items:
    - elasticsearch
    - kibana4

- name: Start Services
  shell: systemctl start {{ item }}
  with_items:
    - kibana4
    - elasticsearch

- name: Install NPM
  yum:  name=npm state=present

- name: Install Elasticdump
  npm: name=elasticdump global=yes state=latest

- copy: src=kibana-export.json dest=/root/kibana-export.json

- name: Import Kibana Dashboard / Visualisation
  shell: 'elasticdump --input=/root/kibana-export.json --output=http://localhost:9200/.kibana --type=data'
