---
- name: Install PIP Dependencies
  pip: name=APScheduler version=3.0.3

- name: Install Packages
  yum: name={{ item }} enablerepo=hermes-ci,epel
  with_items:
    - hermes_ui-*-{{ hermes_image_version }}
    - hermes_aws-*-{{ hermes_image_version }}
    - hermes_cms-*-{{ hermes_image_version }}

- name: Install Config Bucket
  copy: src=config-bucket dest=/etc/sysconfig/config-bucket owner=root group=root mode=0644

- name: Install apache config
  copy: src=hermes_cms.conf dest=/etc/httpd/conf.d/ owner=root group=root mode=0644

- name: Create Folder
  file: path=/var/www/hermes_cms state=directory owner=apache group=apache

- name: Install wsgi
  copy: src=hermes_cms.wsgi dest=/var/www/hermes_cms/hermes_cms.wsgi owner=apache group=apache mode=0444

- name: Automatically Start Apache
  service: name=httpd enabled=yes state=started

- name: Install service scripts
  template: src=templates/upstart.service dest=/usr/lib/systemd/system/{{ item.name }}.service
  with: services

- name: Ensure permissions are setup
  command: setsebool -P httpd_can_network_connect=On
