---
- name: Install Packages
  yum: name={{ item }} enablerepo=epel
  with_items:
    - git
    - nodejs
    - npm
    - jq
    - xorg-x11-server-Xvfb
    - pandoc
    - doxygen
    - rpm-build
    - createrepo
    - wget
    - java-1.7.0-openjdk

- name: Install PIP Packages
  pip: name={{ item }}
  with_items:
    - doxypy
    - pylint
    - tox
    - awscli

- name: Install Packer
  include: install_packer.yml
